### ISSUE TITLE
Add 'message' property to errors.

### ISSUE THREAD

**Issue by YuriGor** [blackflux/secure-chest#245]
Now, just to have an idea what's going on, when 'internal error' returned from API request, 
I need to try/catch call for `unlockObj` and check in the catch block if the exception is instanceof any kind of error listed in the docs. If so - I have to add message property to error, so json response will make some sense:
```js
decrypt: (token) => {
    try {
      return chester().unlockObj(token);
    } catch (exc) {
      if (exc instanceof ChestErrors.DecryptionExpiredError) {
        exc.message = 'Encrypted data expired.';
      }
      if (exc instanceof ChestErrors.DecryptionIntegrityError) {
        exc.message += 'Invalid encrypted data or incorrect secret or name.';
      }
      if (exc instanceof ChestErrors.DecryptionSignatureError) {
        exc.message += 'Signature did not match.';
      }
      if (exc instanceof ChestErrors.DecryptionTimeTravelError) {
        exc.message += 'Encrypted data is not valid yet.';
      }
      if (exc instanceof ChestErrors.DecryptionGunzipError) {
        exc.message += 'Encrypted data compression error.';
      }
      if (exc instanceof ChestErrors.DecryptionGunzipError) {
        exc.message += 'JSON parse of decrypted data failed.';
      }
      if (!exc.message) {
        exc.message = 'Mysterious decryption error.';
      }
      throw exc;
    }
  }
```
If saying so much is possibly dangerous because an evil guy will be better informed, then make this verbose mode optional, so it can be enabled for the development stage.

**Comment by simlu** [comment]
So this would be relatively easy achieved by updating
https://github.com/blackflux/secure-chest/blob/master/src/errors.js

Should be a very generic fix (we could set `message=classname`

**Comment by YuriGor** [comment]
May I propose a PR for this, or you'd prefer to think twice or more and do it yourself (or possibly don't or maybe later)?

**Comment by simlu** [comment]
Would be great if you could! As I said, should be minimal impact and only change this one file (plus test)

**Comment by YuriGor** [comment]
@simlu done but needs review. Something is wrong with PR checks.

**Comment by simlu** [comment]
Released in https://github.com/blackflux/secure-chest/pull/249
