### ISSUE TITLE
Don't enforce `maxAgeInSec` if `expire` flag set

### ISSUE THREAD

**Issue by MacMcIrish** [blackflux/secure-chest#72]
Might also be a good excuse to move the `expire` flag out of the explicit unlock and into the initialization?

When this is updated, it would also make sense to update the docs, there is a disconnect between what is available for `lock` and `unlock` options and what is described in the [docs](https://github.com/blackflux/secure-chest/tree/4106db36d49fd021b36d629246f8f602dfb8c298#functions)
(ie: `expire` is defined as a valid option for both, but only available to `unlock`)

**Comment by simlu** [comment]
Have to carefully consider what makes sense here. There is some bad, some good and some ugly :)

**Comment by simlu** [comment]
The idea is that a token always has an expiration date. However one might choose to ignore it.

Not planning on changing that logic, so I'm closing this unless we can up with a really good use case that isn't already solved :)
